### ISSUE TITLE
Meals EPIC

### ISSUE THREAD

**Issue by milevy1** [milevy1/quantified-self-be#28]
Meals endpoints
- [x] GET /api/v1/meals
- [x] GET /api/v1/meals/:meal_id/foods
- [x] POST /api/v1/meals/:meal_id/foods/:id
- [x] DELETE /api/v1/meals/:meal_id/foods/:id
