### ISSUE TITLE
Foods EPIC

### ISSUE THREAD

**Issue by milevy1** [milevy1/quantified-self-be#5]
- [x] GET /api/v1/foods
- [x] GET /api/v1/foods/:id
- [x] POST /api/v1/foods
- [x] PATCH /api/v1/foods/:id
- [x] DELETE /api/v1/foods/:id
